# Generated by Django 5.2.12 on 2026-04-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_make_subject_non_nullable'),
        ('subjects', '0003_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='subjects.topic'),
        ),
    ]
