# Generated by Django 5.2.12 on 2026-03-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('conducting_body', models.CharField(blank=True, help_text='Organisation that conducts the exam (e.g. UPSC, NTA).', max_length=200)),
                ('frequency', models.CharField(blank=True, help_text='How often the exam is held (e.g. Annual, Biannual).', max_length=50)),
                ('official_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'examinator_exam',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='subjects.subject')),
            ],
            options={
                'db_table': 'examinator_exam_subject',
                'ordering': ['exam', 'subject'],
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exams', through='exams.ExamSubject', to='subjects.subject'),
        ),
    ]
