# Generated by Django 5.2.12 on 2026-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examquestion_examquestionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'examinator_exam_subject_catalog',
                'ordering': ['name'],
            },
        ),
    ]
