# Generated by Django 5.2.12 on 2026-04-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_populate_exam_subject_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exams', through='exams.ExamSubject', to='exams.examsubjectcatalog'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.examsubjectcatalog'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exams.examsubjectcatalog'),
        ),
    ]
