# Generated by Django 5.2.12 on 2026-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAPICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('caller', models.CharField(blank=True, help_text='Feature or task that triggered this call (e.g. exam_questions).', max_length=100)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('input_cost_usd', models.DecimalField(decimal_places=8, max_digits=12)),
                ('output_cost_usd', models.DecimalField(decimal_places=8, max_digits=12)),
                ('total_cost_usd', models.DecimalField(decimal_places=8, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'examinator_gemini_api_call',
                'ordering': ['-created_at'],
            },
        ),
    ]
