# Copyright 2026 BigSecret1
#
# Licensed under the Apache License, Version 2.0

from django.conf import settings
from django.db import models


class DailyFunFact(models.Model):
    '''One fun fact per user per calendar day, generated by Gemini.

    Cached so we only call the model once per user per day regardless of
    how many times the dashboard is loaded.
    '''

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='fun_facts',
    )
    date = models.DateField()
    fact = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'date')
        ordering = ['-date']
        db_table = 'examinator_daily_fun_fact'

    def __str__(self):
        return f'FunFact({self.user_id}, {self.date})'
