# Generated by Django 5.2.12 on 2026-03-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_seed_subjects_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='subjects.topic')),
            ],
            options={
                'db_table': 'examinator_subtopic',
                'ordering': ['topic', 'name'],
                'unique_together': {('topic', 'name')},
            },
        ),
    ]
