# Generated by Django 5.2.12 on 2026-04-25 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of short objective strings.')),
                ('source_filename', models.CharField(blank=True, default='', help_text='Original PDF filename, for the user library display.', max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('generation_mode', models.CharField(choices=[('text', 'Text'), ('vision', 'Vision')], default='text', help_text='Text mode for digital PDFs, vision mode for scanned PDFs.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examinator_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('notes', 'Notes generation')], default='notes', help_text='What the upload was intended for.', max_length=30)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes.')),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Null if the upload was rejected before parsing.', null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('rejection_reason', models.CharField(blank=True, choices=[('', 'OK'), ('not_pdf', 'Not a PDF'), ('over_size_limit', 'Over file-size limit'), ('over_page_limit', 'Over page-count limit'), ('too_little_text', 'Too little extractable text'), ('daily_limit_exceeded', 'Daily upload limit exceeded'), ('other', 'Other')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_activities', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, help_text='The note created from this upload (only when accepted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_activities', to='notes.note')),
            ],
            options={
                'db_table': 'examinator_file_upload_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 star rating of the note generation, if applicable.', null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, help_text='Set when the feedback is about a specific generated note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='notes.note')),
            ],
            options={
                'db_table': 'examinator_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='notes.note')),
            ],
            options={
                'db_table': 'examinator_note_flashcard',
                'ordering': ['note', 'position'],
            },
        ),
        migrations.CreateModel(
            name='NoteKeyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_terms', to='notes.note')),
            ],
            options={
                'db_table': 'examinator_note_key_term',
                'ordering': ['note', 'position'],
            },
        ),
        migrations.CreateModel(
            name='NoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('overview', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0, help_text='Sort order within the note (0 = first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='notes.note')),
            ],
            options={
                'db_table': 'examinator_note_section',
                'ordering': ['note', 'position'],
            },
        ),
        migrations.CreateModel(
            name='NoteSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('content_md', models.TextField(help_text='Markdown-formatted explanation of this concept.')),
                ('examples', models.JSONField(blank=True, default=list, help_text='List of short example strings illustrating the concept.')),
                ('key_takeaways', models.JSONField(blank=True, default=list, help_text='List of short takeaway bullets a student should memorize.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='notes.notesection')),
            ],
            options={
                'db_table': 'examinator_note_subtopic',
                'ordering': ['section', 'position'],
            },
        ),
        migrations.CreateModel(
            name='UserUploadQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(help_text='Maximum file uploads allowed per UTC day.')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('unlimited', 'Unlimited')], default='free', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Admin note about why this override exists.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examinator_user_upload_quota',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date in UTC.')),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examinator_file_upload_daily_usage',
                'ordering': ['-date', 'user'],
                'indexes': [models.Index(fields=['user', '-date'], name='examinator__user_id_7179aa_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='examinator__user_id_239b55_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status'], name='examinator__status_74bace_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadactivity',
            index=models.Index(fields=['user', '-created_at'], name='examinator__user_id_34c6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadactivity',
            index=models.Index(fields=['status'], name='examinator__status_28c8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadactivity',
            index=models.Index(fields=['purpose'], name='examinator__purpose_3b4fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', '-created_at'], name='examinator__user_id_9d9699_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['note'], name='examinator__note_id_5f12ac_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='examinator__rating_14f4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='noteflashcard',
            index=models.Index(fields=['note', 'position'], name='examinator__note_id_46572a_idx'),
        ),
        migrations.AddIndex(
            model_name='notekeyterm',
            index=models.Index(fields=['note', 'position'], name='examinator__note_id_24f266_idx'),
        ),
        migrations.AddIndex(
            model_name='notesection',
            index=models.Index(fields=['note', 'position'], name='examinator__note_id_e03bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='notesubtopic',
            index=models.Index(fields=['section', 'position'], name='examinator__section_844cb1_idx'),
        ),
    ]
